---
repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.7

  - repo: local
    hooks:
      - id: pep8
        name: pep8
        entry: tox -e pep8
        language: system
        types: [python]

      - id: unit_tests
        name: unit_tests
        entry: tox -e py37-unit
        language: system
        types: [python]
